    /*
    #include <iostream>
    #include <string> 
    #include <windows.h>
    #include <stdlib.h>

    using namespace std; 
    const int numberOfPokemon = 10 ;
    const int numberOfAttacks = 4 ;
    string poke_Name[numberOfPokemon] = {"Bulbasaur", "Charmander","Squirtle","Pikachu","Bellsprout","Growlithe","Horsea","Voltorb","Ditto","Mewtwo"} ;
    string species[numberOfPokemon] = {"Seed Pookemon","Lizard Pokemon","Tiny Turtle Pokemon","Mouse Pokemon","Flower Pokemon","Puppy Pokemon","Dragon Pokemon","Ball Pokemon","Transform Pokemon","Genetic Pokemon"};
    string type[numberOfPokemon] = {"Grass / Poison","Fire","Water","Electric","Grass / Poison","Fire","Water","Electric", "Normal","Psychic"} ;
    string attacks[numberOfAttacks] = {"Physical","Physical","Special","Normal"};

    HANDLE hconsole = GetStdHandle(STD_OUTPUT_HANDLE);
class Characteristics{
        
    public :
        Characteristics() {

        }

    void display_Name(int input) {
        cout << "Name Of The Pokemon: - " << poke_Name[input] << endl ;
        cout << endl ;
    }

    void display_Species(int input) {
        cout << "Species Of The Pokemon: - " << species[input] << endl ;
        cout << endl ;
    }

    void display_AttackTypes(int input) {
        cout << "These are " <<  poke_Name[input] << "'s Attack Types. " << endl ;
        for (int i = 0 ; i < 4 ; i++) {
            cout << "Attack ["<< i+1 << "] =>" << attacks[i] << " | " ;
        }
        cout << endl ;
    }

    void display_DispAndChar(int input) {
        switch(input) {
            case 0 : 
                cout << "Description of " << poke_Name[0] << endl ;
                cout << "   Bulbasaur resembles a small, squatting dinosaur that walks on four legs, but bears three claws on each of its feet and has no tail." << endl ; 
                cout << "It also has large, red eyes and very sharp teeth. Its skin is a light, turquoise color with dark, green spots. It has three claws. " << endl ;
                cout << endl ;
                cout << "Characteristics of " << poke_Name[0] << endl ;
                cout << "   Bulbasaur has a \"bulb\" on its back that grows steadily larger as it matures. This bulb contains a seed which uses photosynthesis" << endl ; 
                cout << "to supply Bulbasaur with energy. Its bulb is also used to store the energy that the seed absorbs, which can be used when it is necessary." << endl ;
                cout << endl ;
            break;
            case 1 : 
                cout << "Description of " << poke_Name[1] << endl ;
                cout << "   Charmander is a small, bipedal, dinosaur-like Pokémon. Most of its body is colored orange, while its underbelly is a pale" << endl ; 
                cout << "light-yellow color. Charmander, like its evolved forms, has a flame that constantly burns on the end of its tail." << endl ;
                cout << endl ;
                cout << "Characteristics of " << poke_Name[1] << endl ;
                cout << "   The power of its flame attacks can be gauged by the size of the flame on its tail. " << endl ;
                cout << endl ;
            break;
            case 2 : 
                cout << "Description of " << poke_Name[2] << endl ;
                cout << "   Squirtle is a small, light-blue Pokémon with an appearance like a turtle. With its aerodynamic shape and grooved surface," << endl ;
                cout << "Squirtle's shell helps it wade through the water very quickly. It also offers protection in battle. Unlike a turtle, Squirtle " << endl ; 
                cout << "is ordinarily bipedal. " << endl ;
                cout << endl ;
                cout << "Characteristics of " << poke_Name[2] << endl ;
                cout << "   Its shell is highly sturdy, and it can hide within its shell to protect itself from physical attacks." << endl ;
                cout << endl ;
            
            break;
            case 3 : 
                cout << "Description of " << poke_Name[3] << endl ;
                cout << "   Pikachu are small, chubby, and incredibly cute mouse-like Pokémon. They are almost completely covered by yellow fur." << endl ; 
                cout << "They have long yellow ears that are tipped with black. A Pikachu's back has two brown stripes, and its large tail is" << endl ; 
                cout << "notable for being shaped like a lightning bolt. " << endl ;
                cout << endl ;
                cout << "Characteristics of " << poke_Name[3] << endl ;
                cout << "   Pikachus are usually friendly creatures that love to be cuddled. They love having their tails rubbed, especially at the base " << endl ;
                cout << "they also like being stroked. However, if threatened or angered, this Pokémon can be quite aggressive." << endl ;
                cout << endl ;
            break;
            case 4 : 
                cout << "Description of " << poke_Name[4] << endl ;
                cout << "   Bellsprout is a plant-like Pokémon. The body is a thin brown root and stem system. Bellsprout has two root-like legs. It has" << endl ; 
                cout << "two leaves on each side. Its head is yellow and shaped like a bulb, the tip is colored pink, and it has the smallest amount " << endl ;
                cout << "of dirt on its feet. " << endl ;
                cout << endl ;
                cout << "Characteristics of " << poke_Name[4] << endl ;
                cout << "   It is said to ensnare its prey in its vines and devour it, and can also spit a highly corrosive fluid that can melt even iron. " << endl ;
                cout << "This Pokémon prefers hot and humid environments, since it can absorb more moisture from the ground by planting its root-like feet. " << endl ;
                cout << endl ;
            break;
            case 5 : 
                cout << "Description of " << poke_Name[5] << endl ;
                cout << "   Growlithe resembles a puppy. It has bright orange fur with black stripes. Its belly, tail, and fluff on top of its head are a " << endl ;
                cout << "cream color. There are no gender differences. Much like Vulpix, its shiny form is a yellow/golden color." << endl ;
                cout << endl ;
                cout << "Characteristics of " << poke_Name[5] << endl ;
                cout << "   Naturally loyal and protective, if it is improperly trained, it often bites without warning or unprovoked. " << endl ;
                cout << endl ;
            break;
            case 6 : 
                cout << "Description of " << poke_Name[6] << endl ;
                cout << "   Horsea is a Water-type Pokémon that resembles a seahorse. It is a small, light blue seahorse with tiny scales. Its belly and fin" << endl ; 
                cout << "are cream colored. Its tail is always curled up tightly, and it has a single fin on its back that is used for locomotion in the water. " << endl ;
                cout << endl ;
                cout << "Characteristics of " << poke_Name[6] << endl ;
                cout << "   If they sense trouble, they spit ink towards the instigator. If the enemy is too strong, it quickly swims to safety. When they " << endl ;
                cout << "are a safe location, they can be seen playfully tangling their tails together." << endl ;
                cout << endl ;
            break;
            case 7 : 
                cout << "Description of " << poke_Name[7] << endl ;
                cout << "   Voltorb are Pokémon that look like a large Poké Ball. Spherical in shape, Voltorb's top half is colored red while its bottom half" << endl ; 
                cout << "is white. Voltorb do not have much else in features besides its eyes, which usually indicate that it is angry." << endl ;
                cout << endl ;
                cout << "Characteristics of " << poke_Name[7] << endl ;
                cout << "   Voltorb can have the special ability Soundproof or the special ability Static. This Pokémon looks" << endl ; 
                cout << "just like a Poké Ball. It is also dangerous because it may electrocute or explode on touch. " << endl ;
                cout << endl ;
            break;
            case 8 : 
                cout << "Description of " << poke_Name[8] << endl ;
                cout << "   Ditto's appearance is very plain. It is a simple, pinkish-purple, amorphous blob, with two small dots as eyes and a long, curved mouth. " << endl ;
                cout << endl ;
                cout << "Characteristics of " << poke_Name[8] << endl ;
                cout << "   Ditto will transform into anything it sees, even inanimate objects. When it sees an enemy, it will change its DNA code to match theirs. " << endl ;
                cout << "It avoid being attacked while sleeping by changing its appearance to look like a rock." << endl ;
                cout << endl;
            break;
            case 9 : 
                cout << "Description of " << poke_Name[9] << endl ;
                cout << "   Mewtwo is a bipedal feline-like Pokémon. Its appearance is loosely based on Mew, with a more of a mutated humanoid look in addition" << endl ; 
                cout << "to its feline traits. Its body is purple and it has three fingers on each hand. Mewtwo projects a faint purple aura when at full power. " << endl ;
                cout << endl ;
                cout << "Characteristics of " << poke_Name[9] << endl ;
                cout << "   As evidence of its immense power, Mewtwo is by far one of the most domineering Pokémon in the series. It's power is so great to the " << endl ;
                cout << "point where it can endure immense torture in Mewtwo Returns, and teleport a lake miles long underground!" << endl ;
                cout << "In fact, it general nature is so complex that it borderlines that of human levels with itself capable of learning and" << endl ;
                cout << "evolving just to get the upper hand in battle. Indeed, Mewtwo's title of " << endl ;
                cout << "\"The World's Most Powerful Pokémon\" shouldn't be undermined. " << endl ;
                cout << endl ;
            break;
        }
    }

    void display_Type(int input) {
        cout << "Type Of The Pokemon: - " << type[input] << endl ;
        cout << endl ;
    }

    void display_diagram(int input) {
        switch (input) {
            case 0 :
                SetConsoleTextAttribute(hconsole,2) ;
                Sleep(100);            
                cout << "                                           /" << endl ;
                Sleep(100);
                cout << "                        _,.------....___,.' ',.-." << endl ;
                Sleep(100);
                cout << "                     ,-'          _,.--\"        |" << endl ;
                Sleep(100);
                cout << "                   ,'         _.-'              ." << endl ;
                Sleep(100);
                cout << "                  /   ,     ,'                   `" << endl ;
                Sleep(100);
                cout << "                 .   /     /                     ``." << endl ;
                Sleep(100);
                cout << "                 |  |     .                       \\.\\" << endl ;
                Sleep(100);
                SetConsoleTextAttribute(hconsole,11) ;
                cout << "       ____      |___._.  |       __               \\ `." << endl ;
                Sleep(100);
                cout << "     .'    `---\"\"       ``\"-.--\"'`  \\               .  \\" << endl ;
                Sleep(100);
                cout << "    .  ,            __               `              |   ." << endl ;
                Sleep(100);
                cout << "    `,'         ,-\"'  .               \\             |    L" << endl ;
                Sleep(100);
                cout << "   ,'          '    _.'                -._          /    |" << endl ;
                Sleep(100);
                cout << "  ,`-.    ,\".   `--'                      >.      ,'     |" << endl ;
                Sleep(100);
                cout << " . .'\\'   `-'       __    ,  ,-.         /  `.__.-      ,'" << endl ;
                Sleep(100);
                cout << " ||:, .           ,'  ;  /  / \\ `        `.    .      .'/" << endl ;
                Sleep(100);
                cout << " j|:D  \\          `--'  ' ,'_  . .         `.__, \\   , /" << endl ;
                Sleep(100);
                cout << "/ L:_  |                 .  \"' :_;                `.'.'" << endl ;
                Sleep(100);
                cout << ".    \"\"'                  \"\"\"\"\"'                    V" << endl ;
                Sleep(100);
                cout << " `.                                 .    `.   _,..  `" << endl ;
                Sleep(100);
                cout << "   `,_   .    .                _,-'/    .. `,'   __  `" << endl ;
                Sleep(100);
                cout << "    ) \\`._        ___....----\"'  ,'   .'  \\ |   '  \\  ." << endl ;
                Sleep(100);
                cout << "   /   `. \"`-.--\"'         _,' ,'     `---' |    `./  |" << endl ;
                Sleep(100);
                cout << "  .   _  `\"\"'--.._____..--\"   ,             '         |" << endl ;
                Sleep(100);
                cout << "  | .\" `. `-.                /-.           /          ," << endl ;
                Sleep(100);
                cout << "  | `._.'    `,_            ;  /         ,'          ." << endl ;
                Sleep(100);
                cout << " .'          /| `-.        . ,'         ,           ," << endl ;
                Sleep(100);
                cout << " '-.__ __ _,','    '`-..___;-...__   ,.'\\ ____.___.'" << endl ;
                Sleep(100);
                cout << " `\"^--'..'   '-`-^-'\"--    `-^-'`.''\"\"\"\"\"`.,^.`.--' mh" << endl ;
                SetConsoleTextAttribute(hconsole,15) ;
                cout << endl;
            break;
            case 1 :
                SetConsoleTextAttribute(hconsole,12) ;
                Sleep(100);
                cout << "                                   _.--""`-.. " << endl;
                Sleep(100);
                cout << "                                 ,'          `." << endl;
                Sleep(100);
                cout << "                               ,'          __  `." << endl;
                Sleep(100);
                cout << "                              /|          \" __   \\" << endl;
                Sleep(100);
                cout << "                             , |           / |.   ." << endl;
                Sleep(100);
                cout << "                             |,'          !_.'|   |" << endl;
                Sleep(100);
                cout << "                           ,'             '   |   |" << endl;
                Sleep(100);
                cout << "                          /              |`--'|   |" << endl;
                Sleep(100);
                cout << "                         |                `---'   |" << endl;
                Sleep(100);
                cout << "                          .   ,                   |                       ,\"." << endl;
                Sleep(100);
                cout << "                           ._     '           _'  |                    , ' \\ ` " << endl;
                Sleep(100);
                cout << "                       `.. `.`-...___,...---\"\"    |       __,.        ,`\"   L,| " << endl;
                Sleep(100);
                cout << "                       |, `- .`._        _,-,.'   .  __.-'-. /        .   ,    \\" << endl;
                Sleep(100);
                cout << "                     -:..     `. `-..--_.,.<       `\"      / `.        `-/ |   ." << endl;
                Sleep(100);
                cout << "                       `,         \"\"\"\"'     `.              ,'         |   |  ',," << endl;
                Sleep(100);
                cout << "                         `.      '            '            /          '    |'. |/" << endl;
                Sleep(100);
                cout << "                           `.   |              \\       _,-'           |       ''" << endl;
                Sleep(100);
                cout << "                             `._'               \\   '\"\\                .      |" << endl;
                Sleep(100);
                cout << "                                |                '     \\                `._  ,'" << endl;
                Sleep(100);
                cout << "                                |                 '     \\                 .'|" << endl;
                Sleep(100);
                cout << "                                |                 .      \\                | |" << endl;
                Sleep(100);
                cout << "                                |                 |       L              ,' |" << endl;
                Sleep(100);
                cout << "                                `                 |       |             /   ' " << endl;
                Sleep(100);
                cout << "                                 \\                |       |           ,'   / " << endl;
                Sleep(100);
                cout << "                              ,' \\               |  _.._ ,-..___,..-'    ,'" << endl;
                Sleep(100);
                cout << "                             /     .             .      `!             ,j'" << endl;
                Sleep(100);
                cout << "                            /       `.          /        .           .'/" << endl;
                Sleep(100);
                cout << "                           .          `.       /         |        _.'.'" << endl;
                Sleep(100);
                cout << "                            `.          7`'---'          |------\"'_.'" << endl;
                Sleep(100);
                cout << "                           _,.`,_     _'                ,''-----\"'" << endl;
                Sleep(100);
                cout << "                       _,-_    '       `.     .'      ,\\ " << endl;
                Sleep(100);
                cout << "                       -\" /`.         _,'     | _  _  _.| " << endl;
                Sleep(100);
                cout << "                        \"\"--'---\"\"\"\"\"'        `' '! |! /" << endl;
                Sleep(100);
                cout << "                                               `\" \" -' mh" << endl;
                SetConsoleTextAttribute(hconsole,15) ;
                cout << endl ;
            break;
            case 2 :
                SetConsoleTextAttribute(hconsole,11) ;
                Sleep(100);
                cout << "                _,........__" << endl ;
                Sleep(100);
                cout << "              -'            \"`-. " << endl ;
                Sleep(100);
                cout << "            ,'                   `-." << endl ;
                Sleep(100);
                cout << "          ,'                        \\ " << endl ;
                Sleep(100);
                cout << "        ,'                           ." << endl ;
                Sleep(100);
                cout << "        .'\\               ,"".       `" << endl ;
                Sleep(100);
                cout << "       ._.'|             / |  `       \\ " << endl ;
                Sleep(100);
                cout << "       |   |            `-.'  ||       `." << endl ;
                Sleep(100);
                cout << "       |   |            '-._,'||       | \\ " << endl ;
                Sleep(100);
                cout << "       .`.,'             `..,'.'       , |`-." << endl ;
                Sleep(100);
                cout << "       l                       .'`.  _/  |   `." << endl ;
                Sleep(100);
                cout << "       `-.._'-   ,          _ _'   -\" \\  .     `" << endl ;
                Sleep(100);
                cout << "  `.\"\"\"\"\"'-.`-...,---------','         `. `....__." << endl ;
                Sleep(100);
                cout << "  .'        `\"-..___      __,'\\          \\  \\     \\" << endl ;
                Sleep(100);
                cout << "  \\_ .          |   `""""'    `.           . \\     \\" << endl ;
                Sleep(100);
                cout << "     `.          |              `.          |  .     L" << endl ;
                Sleep(100);
                cout << "       .        |`--...________.'.        j   |     |" << endl ;
                Sleep(100);
                cout << "         ._    .'      |          `.     .|   ,     |  " << endl ;
                Sleep(100);
                cout << "           `--,\\       .            `7""' |  ,      |  " << endl ;
                Sleep(100);
                cout << "              ` `      `            /     |  |      |    _,-'\"\"\"`-. " << endl ;
                Sleep(100);
                cout << "               \\ `.     .          /      |  '      |  ,'          `. " << endl ;
                Sleep(100);
                cout << "                 \\  v.__  .        '       .   \\    /| /              \\  " << endl ;
                Sleep(100);
                cout << "                   \\/    `""\"""""""`.       \\   \\  /.''                |  " << endl ;
                Sleep(100);
                cout << "                    `        .        `._ ___,j.  `/ .-       ,---.     | " << endl ;
                Sleep(100);
                cout << "                    ,`-.      \\         .\"     `.  |/        j     `    |  " << endl ;
                Sleep(100);
                cout << "                   /    `.     \\       /         \\ /         |     /    j  " << endl ;
                Sleep(100);
                cout << "                  |       `-.   7-.._ .          |\"          '         /  " << endl ;
                Sleep(100);
                cout << "                  |          `./_    `|          |            .     _,'  " << endl ;
                Sleep(100);
                cout << "                  `.           / `----|          |-............`---'  " << endl ;
                Sleep(100);
                cout << "                    \\          \\      |          |  " << endl ;
                Sleep(100);
                cout << "                   ,'           )     `.         |  " << endl ;
                Sleep(100);
                cout << "                    7____,,..--'      /          |  " << endl ;
                Sleep(100);
                cout << "                                      `---.__,--.'mh" << endl ;
                SetConsoleTextAttribute(hconsole,15) ;
                cout << endl ;
            break ;
            case 3 :
                SetConsoleTextAttribute(hconsole,6) ;
                Sleep(100);
                cout << "                                             ,-." << endl ;
                Sleep(100);
                cout << "                                          _.|  '" << endl ;
                Sleep(100);
                cout << "                                        .'  | /" << endl ;
                Sleep(100);
                cout << "                                      ,'    |'" << endl ;
                Sleep(100);
                cout << "                                     /      /" << endl ;
                Sleep(100);
                cout << "                       _..----\"\"---.'      /" << endl ;
                Sleep(100);
                cout << " _.....---------...,-\"\"                  ,'" << endl ;
                Sleep(100);
                cout << " `-._  \\                                /" << endl ;
                Sleep(100);
                cout << "     `-.+_            __           ,--. ." << endl ;
                Sleep(100);
                cout << "          `-.._     .:  ).        (`--\"| \\" << endl ;
                Sleep(100);
                cout << "               7    | `\" |         `...'  \\" << endl ;
                Sleep(100);
                cout << "               |     `--'     '+\"        ,\". ,\"\"-" << endl ;
                Sleep(100);
                cout << "               |   _...        .____     | |/    '" << endl ;
                Sleep(100);
                cout << "          _.   |  .    `.  '--\"   /      `./     j" << endl ;
                Sleep(100);
                cout << "         \\' `-.|  '     |   `.   /        /     /" << endl ;
                Sleep(100);
                cout << "         '     `-. `---\"      `-\"        /     /" << endl ;
                Sleep(100);
                cout << "          \\       `.                  _,'     /" << endl ;
                Sleep(100);
                cout << "           \\        `                        ." << endl ;
                Sleep(100);
                cout << "            \\                                j" << endl ;
                Sleep(100);
                cout << "             \\                              /" << endl ;
                Sleep(100);
                cout << "              `.                           ." << endl ;
                Sleep(100);
                cout << "                +                          \\" << endl ;
                Sleep(100);
                cout << "                |                           L" << endl ;
                Sleep(100);
                cout << "                |                           |" << endl ;
                Sleep(100);
                cout << "                |  _ /,                     |" << endl ;
                Sleep(100);
                cout << "                | | L)'..                   |" << endl ;
                Sleep(100);
                cout << "                | .    | `                  |" << endl ;
                Sleep(100);
                cout << "                '  \\'   L                   '" << endl ;
                Sleep(100);
                cout << "                 \\  \\   |                  j" << endl ;
                Sleep(100);
                cout << "                  `. `__'                 /" << endl ;
                Sleep(100);
                cout << "                _,.--.---........__      /" << endl ;
                Sleep(100);
                cout << "               ---.,'---`         |   -j\"" << endl ;
                Sleep(100);
                cout << "                .-'  '....__      L    |" << endl ;
                Sleep(100);
                cout << "              \"\"--..    _,-'       \\ l||" << endl ;
                Sleep(100);
                cout << "                  ,-'  .....------. `||'" << endl ;
                Sleep(100);
                cout << "               _,'                /" << endl ;
                Sleep(100);
                cout << "             ,'                  /" << endl ;
                Sleep(100);
                cout << "            '---------+-        /" << endl ;
                Sleep(100);
                cout << "                     /         /" << endl ;
                Sleep(100);
                cout << "                   .'         /" << endl ;
                Sleep(100);
                cout << "                 .'          /" << endl ;
                Sleep(100);
                cout << "               ,'           /" << endl ;
                Sleep(100);
                cout << "             _'....----\"\"\"\"\" mh" << endl ;
                SetConsoleTextAttribute(hconsole,15) ;
                cout << endl ;
            break ;
            case 4 :
                SetConsoleTextAttribute(hconsole,6) ;
                Sleep(100);
                cout  << "                _.--\"'\"\"\"--._" << endl ;
                Sleep(100);
                cout  << "              .\"             `." << endl ;
                Sleep(100);
                cout  << "             /                 ." << endl ;
                Sleep(100);
                cout  << "            j                   ." << endl ;
                Sleep(100);
                cout  << "            |                   |" << endl ;
                Sleep(100);
                cout  << "            |                   |" << endl ;
                Sleep(100);
                cout  << "            | (')              j" << endl ;
                Sleep(100);
                cout  << "            `                 ,`." << endl ;
                Sleep(100);
                cout  << "             \\               ,^. `." << endl ;
                Sleep(100);
                cout  << "              .             /   \\  ." << endl ;
                Sleep(100);
                cout  << "              |            /     . |" << endl ;
                Sleep(100);
                cout  << "              |          ,'      | |" << endl ;
                Sleep(100);
                SetConsoleTextAttribute(hconsole,12) ;
                cout  << "             ,'---..___ /        | |" << endl ;
                Sleep(100);
                cout  << "            ' `--..___ \"`.      .  |" << endl ;
                Sleep(100);
                cout  << "             `\"--....___.'     /  j__.....__" << endl ;
                Sleep(100);
                SetConsoleTextAttribute(hconsole,2) ;
                cout  << "                              /   |         `." << endl ;
                Sleep(100);
                cout  << "                             / _,------._     `." << endl ;
                Sleep(100);
                cout  << "                            /,+_         `.     `." << endl ;
                Sleep(100);
                cout  << "                          ,'    `-.        \\      ." << endl ;
                Sleep(100);
                cout  << "                         .         `.       \\      \\" << endl ;
                Sleep(100);
                cout  << "                         |           `.     |       \\" << endl ;
                Sleep(100);
                cout  << "                         |             `.   |_,..__  ." << endl ;
                Sleep(100);
                cout  << "                         |\\              \\  |      `.|" << endl ;
                Sleep(100);
                cout  << "                         | `.,--------._  \\ |        `" << endl ;
                Sleep(100);
                cout  << "                         |  |           `. \\|" << endl ;
                Sleep(100);
                cout  << "                         |  |             `.|" << endl ;
                Sleep(100);
                cout  << "                         |  |" << endl ;
                Sleep(100);
                cout  << "                         |  |" << endl ;
                Sleep(100);
                cout  << "                         |. '" << endl ;
                Sleep(100);
                cout  << "                        .' \\ `." << endl ;
                Sleep(100);
                cout  << "                     _,' ,' `. ._" << endl ;
                Sleep(100);
                cout  << "   ---====+,______,.\"_.-'     .  `." << endl ;
                Sleep(100);
                cout  << "   _,..==`'_.+'-\"\"\"\"'         / ^.\\`:._" << endl ;
                Sleep(100);
                cout  << " ,=\"/    ,\"            ....==+ /  `\\  `:." << endl ;
                Sleep(100);
                cout  << "'  /    / |               _+:-'    .|   ``." << endl ;
                Sleep(100);
                cout  << "       '  `.           --\"\"        |'     `\\" << endl ;
                Sleep(100);
                cout  << "                                   ' mh" << endl ;
                SetConsoleTextAttribute(hconsole,15) ;
                cout << endl ;
            break;
            case 5 :
                cout  << "" << endl ;
                cout  << "" << endl ;
                cout  << "" << endl ;
                SetConsoleTextAttribute(hconsole,7) ;
                Sleep(100);
                cout  << "                   _," << endl ;
                Sleep(100);
                cout  << "                 .',_..," << endl ;
                Sleep(100);
                cout  << "               ,'     /,--" << endl ;
                Sleep(100);
                cout  << "             .'       ,./.__" << endl ;
                Sleep(100);
                cout  << "             |_,.----/,,'`.  _" << endl ;
                Sleep(100);
                SetConsoleTextAttribute(hconsole,12) ;
                cout  << "            .'__     //    `...>" << endl ;
                Sleep(100);
                cout  << "       ____//|) |    `      /.'" << endl ;
                Sleep(100);
                cout  << "      (/    `-.-'.._     _,|                 ,.-------.._" << endl ;
                Sleep(100);
                cout  << "      .             `.  '   \\               /            `-._" << endl ;
                Sleep(100);
                cout  << "      `..---._       |       `.            j                 `." << endl ;
                Sleep(100);
                cout  << "        >-,-\"`\"\"'    |        |`\"+-..__    |              -. `-." << endl ;
                Sleep(100);
                cout  << "       ( /|         /____     |  |  |  \\\"\"|+-.._     ___    `.  `." << endl ;
                Sleep(100);
                cout  << "        \" `-..._     \"--,_    |  |  `   | |   | `.-.\"   \"-._  |  -`" << endl ;
                Sleep(100);
                cout  << "             ,'        '_>_   j ,'  '. ,` |,  |   `. `.-v.' `-+..._`." << endl ;
                Sleep(100);
                cout  << "            '.         >       '     | |  ' \\ L     ..`.  '        `._" << endl ;
                Sleep(100);
                cout  << "             '.       /              '|`     \\|      '^,         ..,{ `." << endl ;
                Sleep(100);
                cout  << "            / /      /                '       v          |__    ___,'\"\"" << endl ;
                Sleep(100);
                cout  << "          ,'  >---+-+.        |   __,..--\"`-._          /.-'`\"----'" << endl ;
                Sleep(100);
                cout  << "         /`.       `. '.      |-\"'            `\"--....-'._" << endl ;
                Sleep(100);
                cout  << "       .'___'        `._`,    j             ___,-','      `-..._" << endl ;
                Sleep(100);
                SetConsoleTextAttribute(hconsole,7) ;
                cout  << "  _ _.'    '/.-          '  ,'       __..<\"\"__,.-'              `." << endl ;
                Sleep(100);
                cout  << " `.)         |'---\"\"`.+-.--'-------\"\"-...__  ,-'/ .\"\\          _  |" << endl ;
                Sleep(100);
                cout  << ",\"\\ ,--.  _,-          ` `'                `'\"\"\"'`\"'\"\"\"`--._  . `/" << endl ;
                Sleep(100);
                cout  << " `-`.___.'                                                  `\"-\"'" << endl ;
                Sleep(100);
                cout  << "" << endl ;
                Sleep(100);
                cout << endl ;
                SetConsoleTextAttribute(hconsole,15) ;
            break;
            case 6 :
                SetConsoleTextAttribute(hconsole,11) ;   
                cout  << "                          _,..----.._" << endl ;
                Sleep(100);
                cout  << " ,\"''-.               _.-'           `\"-._" << endl ;
                Sleep(100);
                cout  << ".,-.   `._          ,'    ,---.           `.             _,.." << endl ;
                Sleep(100);
                cout  << "||  \\     `._     ,'    .' |   .            `.     _,.-\"' _,'" << endl ;
                Sleep(100);
                cout  << "||   .       `-._.      |.'|   |            _...-\"'    _,'" << endl ;
                Sleep(100);
                cout  << "''   |           '      |  '   |         --'       _,-'" << endl ;
                Sleep(100);
                cout  << " \\\\  |                  '.'    |                 ,'" << endl ;
                Sleep(100);
                cout  << "  .`.'                   `.    '                (" << endl ;
                Sleep(100);
                cout  << "   `.____                  `--'                  `--..__" << endl ;
                Sleep(100);
                cout  << "         ``\"-.._                                        ``--..__" << endl ;
                Sleep(100);
                cout  << "                |\"                                              ``." << endl ;
                Sleep(100);
                cout  << "                `                             .--\"''\"\"\"'`--------'" << endl ;
                Sleep(100);
                cout  << "                 `.                           \\" << endl ;
                Sleep(100);
                SetConsoleTextAttribute(hconsole,7) ;
                cout  << "     ,-\"'`-._      `-._                 `._    `." << endl ;
                Sleep(100);
                cout  << "    /        `.     ,._`-.._          _,'  `-.   ." << endl ;
                Sleep(100);
                cout  << "   .    _      `.   |  `\"-._`     .-\"'        `-. `." << endl ;
                Sleep(100);
                cout  << "   |     `\"-._   `. |--.._  `._   \\              `. ." << endl ;
                Sleep(100);
                cout  << "   |          `-._ `|     `-._ `-. `.              `'" << endl ;
                Sleep(100);
                cout  << "   `        ._    `/'         `-. `. ." << endl ;
                Sleep(100);
                cout  << "    \\         `\"-.'  .-....__    `. `.`." << endl ;
                Sleep(100);
                cout  << "     .          /    '       `\"-.._   | \\" << endl ;
                Sleep(100);
                cout  << "      `.       /------\\            `  |  \\" << endl ;
                Sleep(100);
                cout  << "        `.___./        `              '   ." << endl ;
                Sleep(100);
                cout  << "             ,          `._        ,-'    |" << endl ;
                Sleep(100);
                cout  << "             |.-\"''\"\"'--.._`\"---'\"/       |" << endl ;
                Sleep(100);
                cout  << "             |  ______      `\"-../        |" << endl ;
                Sleep(100);
                SetConsoleTextAttribute(hconsole,11) ;
                cout  << "             .\"'      `\".       /         '" << endl ;
                Sleep(100);
                cout  << "           ,'            .     /         ." << endl ;
                Sleep(100);
                cout  << "          .              |   .'         /" << endl ;
                Sleep(100);
                cout  << "          |       ,'     |.-'          /" << endl ;
                Sleep(100);
                cout  << "          |       |      '            '" << endl ;
                Sleep(100);
                cout  << "           .       `-..-\"          _,'" << endl ;
                Sleep(100);
                cout  << "            `.                  _,\"" << endl ;
                Sleep(100);
                cout  << "              `._          __.-'" << endl ;
                Sleep(100);
                cout  << "                 `'------\"' mh" << endl ;
                cout << endl ;
                SetConsoleTextAttribute(hconsole,15) ;
            break ;
            case 7:
                SetConsoleTextAttribute(hconsole,12) ;
                cout  << "                         __...--------...__" << endl ;
                Sleep(100);
                cout  << "                    _.--'                  `\"-.." << endl ;
                Sleep(100);
                cout  << "                _.-'                  ,.        `-._" << endl ;
                Sleep(100);
                cout  << "             _,'                    .'  \\           `._" << endl ;
                Sleep(100);
                cout  << "           ,\"                     ,'     .             `." << endl ;
                Sleep(100);
                cout  << "         ,'                      /        `.             `." << endl ;
                Sleep(100);
                cout  << "        /                       .           \\              `." << endl ;
                Sleep(100);
                cout  << "      ,'                         `.._        .               ." << endl ;
                Sleep(100);
                cout  << "     /                               `-._    /`               \\" << endl ;
                Sleep(100);
                cout  << "    /                                    `-._  \\               \\" << endl ;
                Sleep(100);
                cout  << "   /    __,........----...__                 `\"-'               \\" << endl ;
                Sleep(100);
                cout  << "  /.--\"\"                    `'--.._                 ..........." << endl ;
                Sleep(100);
                cout  << " j                                 `\"-._            `. /      |  `" << endl ;
                Sleep(100);
                cout  << " '                                      `._           `.      .   ." << endl ;
                Sleep(100);
                cout  << ".                                          `._          `.    '   |" << endl ;
                Sleep(100);
                cout  << "|                                             `.          \\  /    |" << endl ;
                Sleep(100);
                cout  << "|                                               `.         `'     |" << endl ;
                Sleep(100);
                cout  << "|                                                 `.              |" << endl ;
                Sleep(100);
                SetConsoleTextAttribute(hconsole,7) ;
                cout  << "|                                                   `.            |" << endl ;
                Sleep(100);
                cout  << "'                                                     `.          |" << endl ;
                Sleep(100);
                cout  << " .                                                      .         |" << endl ;
                Sleep(100);
                cout  << "                                                         \\        '" << endl ;
                Sleep(100);
                cout  << "  '                                                       \\      '" << endl ;
                Sleep(100);
                cout  << "   .                                                       \\    /" << endl ;
                Sleep(100);
                cout  << "    \\       ____                                            .  /" << endl ;
                Sleep(100);
                cout  << "     \\    .\"    `\"\"-._                                       '/" << endl ;
                Sleep(100);
                cout  << "      `   '           `-.                                   ,'" << endl ;
                Sleep(100);
                cout  << "       `.  `.            `.                               ,'" << endl ;
                Sleep(100);
                cout  << "         `.  .             `.                           .'" << endl ;
                Sleep(100);
                cout  << "           `._`-.            \\                        .'" << endl ;
                Sleep(100);
                cout  << "              `._`._          '                    _,'" << endl ;
                Sleep(100);
                cout  << "                 `._`\"-._     |                 _.\"" << endl ;
                Sleep(100);
                cout  << "                     \"-.._`--'           __,.-\"'" << endl ;
                Sleep(100);
                cout  << "                          `\"\"----------\"' mh" << endl ;
                Sleep(100);
                cout << endl ;
                SetConsoleTextAttribute(hconsole,15) ;
            break ;
            case 8 :
                cout  << "" << endl ;
                SetConsoleTextAttribute(hconsole,13) ;
                Sleep(100);
                cout  << "                                           ,--._" << endl ;
                Sleep(100);
                cout  << "                                        _,'     `." << endl ;
                Sleep(100);
                cout  << "                              ,.-------\"          `." << endl ;
                Sleep(100);
                cout  << "                             /                 \"    `-.__" << endl ;
                Sleep(100);
                cout  << "                            .         \"        _,        `._" << endl ;
                Sleep(100);
                cout  << "                            |            __..-\"             `." << endl ;
                Sleep(100);
                cout  << "                            |        ''\"'                     `._" << endl ;
                Sleep(100);
                cout  << "                            |                                    `\"-." << endl ;
                Sleep(100);
                cout  << "                            '                                        `." << endl ;
                Sleep(100);
                cout  << "                           .                                          |" << endl ;
                Sleep(100);
                cout  << "                          /                                           |" << endl ;
                Sleep(100);
                cout  << "                       _,'                                           ,'" << endl ;
                Sleep(100);
                cout  << "                     ,\"                                             /" << endl ;
                Sleep(100);
                cout  << "                    .                                              /" << endl ;
                Sleep(100);
                cout  << "                    |                                             /" << endl ;
                Sleep(100);
                cout  << "                    |                                            ." << endl ;
                Sleep(100);
                cout  << "                    '                                            |" << endl ;
                Sleep(100);
                cout  << "                     `.                                          |" << endl ;
                Sleep(100);
                cout  << "                       `.                                        |" << endl ;
                Sleep(100);
                cout  << "                         `.                                      '" << endl ;
                Sleep(100);
                cout  << "                           .                                      ." << endl ;
                Sleep(100);
                cout  << "                           |                                       `." << endl ;
                Sleep(100);
                cout  << "                           '                                        |" << endl ;
                Sleep(100);
                cout  << "                         ,'                                         |" << endl ;
                Sleep(100);
                cout  << "                       ,'                                           '" << endl ;
                Sleep(100);
                cout  << "                      /                                _...._      /" << endl ;
                Sleep(100);
                cout  << "                     .                              ,-'      `\"'--'" << endl ;
                Sleep(100);
                cout  << "      ___            |                            ,'" << endl ;
                Sleep(100);
                cout  << "   ,-'   `\"-._     _.'                          ,'" << endl ;
                Sleep(100);
                cout  << "  /           `\"--'             _,....__     _,'" << endl ;
                Sleep(100);
                cout  << " '                            .'        `---'" << endl ;
                Sleep(100);
                cout  << " `                 ____     ,'" << endl ;
                Sleep(100);
                cout  << "  .           _.-'\"    `---'" << endl ;
                Sleep(100);
                cout  << "   `-._    _.\"" << endl ;
                Sleep(100);
                cout  << "       \"\"\"'" << endl ;
                Sleep(100);
                cout << endl ;
                SetConsoleTextAttribute(hconsole,15) ;
            break;
            case 9 :
                cout  << "" << endl ;
                SetConsoleTextAttribute(hconsole,245) ;
                Sleep(100);
                cout  << "                                               `/:+`                      ```                       " << endl ;
                Sleep(100);
                cout  << "                                              :- .+`     `....``        -+-:/:                      " << endl ;
                Sleep(100);
                cout  << "                                              ./. `/--:::-....--:::::-./:   +.                      " << endl ;
                Sleep(100);
                cout  << "                                               `/.  .`              `.:`  `/.                       " << endl ;
                Sleep(100);
                cout  << "                                                `/                       `+`                        " << endl ;
                Sleep(100);
                cout  << "                                                `o                       /.                         " << endl ;
                Sleep(100);
                cout  << "                                                :-                       /.                         " << endl ;
                Sleep(100);
                cout  << "                                               `+                        ./                         " << endl ;
                Sleep(100);
                cout  << "                                               .:                        `+                         " << endl ;
                Sleep(100);
                cout  << "                                               `+    `.`           `     .+                         " << endl ;
                Sleep(100);
                cout  << "                                                :-`-:``.-`      `..` `-.`/.                         " << endl ;
                Sleep(100);
                cout  << "                                                `+``o/o.` `- `- ```:+-/ ./                          " << endl ;
                Sleep(100);
                cout  << "                                                 :- //Nh/. .:-/ .:hNh--.+`                          " << endl ;
                Sleep(100);
                cout  << "                        `-:::::-`                `+```:+ss::.`:/yoo/.``+`                           " << endl ;
                Sleep(100);
                cout  << "                       `+-`   `.+.              `:+-     ``     `     -:                            " << endl ;
                Sleep(100);
                cout  << "                       /-       .o              +.`./-.            `-:-`                            " << endl ;
                Sleep(100);
                cout  << "                       :/       :+:`           ::  --.-::.` ``. `.::.                               " << endl ;
                Sleep(100);
                cout  << "                        :/-...-/:`./:--..`     o   o    s.::-..::-`                                 " << endl ;
                Sleep(100);
                cout  << "                         `..-+-`    -+:..-:-.` + `.+:---o````.+-                                    " << endl ;
                Sleep(100);
                cout  << "                  `...`      :+      `:/-..-//:+:/:-.` `.--:``-:-.-.                                " << endl ;
                Sleep(100);
                cout  << "                -/:-.-:/-``.:/. -      .s:...-/-````.-:`  `..-:-  `:-                               " << endl ;
                Sleep(100);
                cout  << "               .o`     `o/--.  `o      o`     `o`     `/.      -``  -:                              " << endl ;
                Sleep(100);
                cout  << "        ```    -/       /-      +`     s       o`       +`     ` .:` :-                             " << endl ;
                Sleep(100);
                cout  << "    `-//:::://:-s:`   `:o.``    `.   ``++.`  `:/-`      -/     .- -/  +`                            " << endl ;
                Sleep(100);
                cout  << "  `//-`       `-:os+:::----:::.````-/:-.-:::::. ./`     `+      /  +` :/                            " << endl ;
                Sleep(100);
                cout  << " .o.   ``...:.    `:+.       `-::::-`            `+.    `+      `  :` :s                            " << endl ;
                Sleep(100);
                cout  << "`o.  `::----:+/`    `+:                           `/:`   /.      `..``/o                            " << endl ;
                Sleep(100);
                cout  << ":+  `+.       -+`     //                            ./-` `::-..-::-` :./`                           " << endl ;
                Sleep(100);
                cout  << "o.  :/         -o`     /+                             -/.    `    `  /..:                           " << endl ;
                Sleep(100);
                cout  << "y   +.          :+      //                             `::        /. :-`/                           " << endl ;
                Sleep(100);
                cout  << "y   +.           //      o-                              +.       `o``+`/`                          " << endl ;
                Sleep(100);
                cout  << "s`  /:            +/     .o                              -/        .+ .+./`                         " << endl ;
                Sleep(100);
                cout  << "+-  .o             /+`    s.                             -:         -- .+.+`                        " << endl ;
                Sleep(100);
                cout  << "-+   +-             -o:   s`                        ./::-:` .`       `  `/:o`                       " << endl ;
                Sleep(100);
                cout  << " o`  `o.              -///-                      `:/-        ``       ````-/o:                      " << endl ;
                Sleep(100);
                cout  << " .o   `o`                                      `//`              .:-::::::/++s+                     " << endl ;
                Sleep(100);
                cout  << "  :/   `+-                                    -+`                 -:        :+:+-                   " << endl ;
                Sleep(100);
                cout  << "   //    :+`                                 :/`                   +         `o-:+`                 " << endl ;
                Sleep(100);
                cout  << "    :+`   `//`                              :/                     o          `s`-o`                " << endl ;
                Sleep(100);
                cout  << "     -+`    .//-                           -+                     .o           o. -+                " << endl ;
                Sleep(100);
                cout  << "      `+-     `-/:-.                     `-s                      +-           o.  /:               " << endl ;
                Sleep(100);
                cout  << "       `//`      `.-:::---.....-------::::s.                     .o           `s   `s               " << endl ;
                Sleep(100);
                cout  << "         .+:`         ````......``````   :/                     `o.           //    s`              " << endl ;
                Sleep(100);
                cout  << "           -/:`                         `o`                     +-           .o`    s`              " << endl ;
                Sleep(100);
                cout  << "             ./:`                       -/                    `+-           `o.     s`              " << endl ;
                Sleep(100);
                cout  << "               .:/-`                    +.                   `+-           `o-      s               " << endl ;
                Sleep(100);
                cout  << "                 `-/:.`                 o`                  .+-           -+.      `o               " << endl ;
                Sleep(100);
                cout  << "                    `-/:-.`             o`                `//`          ./:`       :-               " << endl ;
                Sleep(100);
                cout  << "                       `.-:::-.``       :`              `:/.          .//.        ./                " << endl ;
                Sleep(100);
                cout  << "                            `.--::::-.-:+`            .:/.         `-/:.        .::`                " << endl ;
                Sleep(100);
                cout  << "                                  `.://:`          `.//.        `-:/-`       .-/-`                  " << endl ;
                Sleep(100);
                cout  << "                                  -/-`          `-/+:.````...-:/s:.      `.-/-.                     " << endl ;
                Sleep(100);
                cout  << "                                 `o         .::::-:---------..` o       `+-`                        " << endl ;
                Sleep(100);
                cout  << "                                  o`      `-:-`                 ::      .+                          " << endl ;
                Sleep(100);
                cout  << "                                  o`     ./.                     +`     +.                          " << endl ;
                Sleep(100);
                cout  << "                                 `o     .o`                      +.     +                           " << endl ;
                Sleep(100);
                cout  << "                                 ::     o.                      `o`     /`                          " << endl ;
                Sleep(100);
                cout  << "                                `o`    :+                      `+-      `+-                         " << endl ;
                Sleep(100);
                cout  << "                                :/     y`                    ./o/-`      `:/.                       " << endl ;
                Sleep(100);
                cout  << "                               `o`     h/-                  -+. `-s`       `//.`                    " << endl ;
                Sleep(100);
                cout  << "                              `o.      y`o`                 o`    o.         `:/:`                  " << endl ;
                Sleep(100);
                cout  << "                              /:       s.o.                 -o.``:s.`           .:/:.`       ````   " << endl ;
                Sleep(100);
                cout  << "                             :/        :o-                   `///-`-:/:.         ...:///::::/::://` " << endl ;
                Sleep(100);
                cout  << "                            :/         `o.`..``                       .:+.        .-:/::/++-`    .+:" << endl ;
                Sleep(100);
                cout  << "                           -+  `://`    `/:..::/-                       `+:`               -+-    `s" << endl ;
                Sleep(100);
                cout  << "                          -o      -+            //                        -//:.```         `/o-:--:." << endl ;
                Sleep(100);
                cout  << "                          /:     `/o-:::::::`   `s                           `-:::::::::--:-`       " << endl ;
                Sleep(100);
                cout  << "                           :/::://-        `:////-                                                  " << endl ;
                Sleep(100);
                cout << endl  ;
                SetConsoleTextAttribute(hconsole,15) ;
            break ;
        }
    }
};
*/